services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: reddit-backend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    networks:
      - main

networks:
  main:
    driver: bridge
