services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: reddit-backend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    depends_on:
      - database
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}
    networks:
      - main

  database:
    image: postgres:17
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reddit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - main

networks:
  main:
    driver: bridge

volumes:
  postgres_data: